-- 0004_jobs: the distributed job queue.
--
-- This is a queue built directly on Postgres. No broker. The reasoning is in
-- DESIGN_DECISIONS.md; the short version is that job state and photo state
-- live in the same database, so "mark this job done and write its result" is
-- one transaction rather than a dual write across two systems.

-- ---------------------------------------------------------------------------
-- workers: one row per running worker process.
--
-- Exists so that (a) a lease can name who holds it, and (b) a worker that
-- stops heartbeating can be identified as dead and its work reclaimed.
-- ---------------------------------------------------------------------------
CREATE TYPE worker_status AS ENUM (
    'active',   -- heartbeating
    'stopped',  -- shut down cleanly, said goodbye
    'dead'      -- stopped heartbeating without saying goodbye
);

CREATE TABLE workers (
    -- Generated by the worker itself at startup, not by the database. A worker
    -- needs an identity before it can insert its own row, and generating it
    -- client-side means a retry of the registration insert is idempotent.
    id       uuid PRIMARY KEY,
    hostname text NOT NULL,
    pid      integer NOT NULL,

    status           worker_status NOT NULL DEFAULT 'active',
    -- Bounded concurrency this worker was configured with, recorded so the
    -- UI can show total capacity across the fleet.
    concurrency      integer NOT NULL DEFAULT 1 CHECK (concurrency > 0),

    started_at        timestamptz NOT NULL DEFAULT now(),
    last_heartbeat_at timestamptz NOT NULL DEFAULT now(),
    stopped_at        timestamptz
);

-- The reaper's query: find active workers whose heartbeat has lapsed.
CREATE INDEX workers_heartbeat_idx
    ON workers (last_heartbeat_at)
    WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- jobs
-- ---------------------------------------------------------------------------
CREATE TYPE job_status AS ENUM (
    'pending',    -- claimable now, or at next_attempt_at
    'running',    -- leased by a worker
    'succeeded',  -- terminal, happy
    'dead'        -- terminal, exhausted max_attempts
);

-- Note there is no 'failed' resting state. A retryable failure returns the row
-- to 'pending' with a future next_attempt_at, which is what keeps the claim
-- query a single indexed read instead of a union over two conditions.

CREATE TABLE jobs (
    -- bigserial, not uuid: jobs are high-volume and ordered. A monotonic
    -- integer gives the claim query a natural tiebreak that is also insertion
    -- order, and keeps the index dense.
    id bigserial PRIMARY KEY,

    job_type text NOT NULL,

    -- Polymorphic target. 'photo' for the per-photo jobs that fan out one per
    -- file; 'library' for the aggregate stages that need a global view.
    -- Keeping both in one table means leases, retries and crash recovery are
    -- written once rather than twice.
    target_type text NOT NULL CHECK (target_type IN ('photo', 'library')),
    target_id   uuid NOT NULL,

    -- Denormalised from the target so progress queries and cascade deletes do
    -- not need a join. A library-scoped job has library_id = target_id.
    library_id uuid NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,

    status   job_status NOT NULL DEFAULT 'pending',
    -- Lower runs sooner. Aggregates get a higher number so the per-photo work
    -- they depend on drains first.
    priority smallint NOT NULL DEFAULT 100,

    attempt_count int NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    max_attempts  int NOT NULL DEFAULT 5 CHECK (max_attempts > 0),

    leased_by        uuid REFERENCES workers(id) ON DELETE SET NULL,
    lease_expires_at timestamptz,

    -- When this job becomes claimable. Set into the future by backoff after a
    -- failure. Defaulting to now() means a freshly enqueued job is immediately
    -- claimable.
    next_attempt_at timestamptz NOT NULL DEFAULT now(),

    last_error text,

    -- Idempotent enqueue key, e.g. 'COMPUTE_FILE_HASH:<uuid>'. See the partial
    -- unique index below.
    dedupe_key text NOT NULL,

    created_at   timestamptz NOT NULL DEFAULT now(),
    started_at   timestamptz,
    completed_at timestamptz,
    updated_at   timestamptz NOT NULL DEFAULT now(),

    -- A leased job must name its holder and its deadline; an unleased one must
    -- have neither. Enforcing the pairing in the schema means a bug in the
    -- claim or release path fails loudly at write time instead of leaving a
    -- job that looks claimed but has no expiry and can never be reaped.
    CONSTRAINT jobs_lease_pairing CHECK (
        (leased_by IS NULL     AND lease_expires_at IS NULL) OR
        (leased_by IS NOT NULL AND lease_expires_at IS NOT NULL)
    )
);

-- THE claim index.
--
-- The claim query filters on status and next_attempt_at, then orders by
-- (priority, id). Partial on 'pending' is the single most important
-- performance decision in the queue: without it the index grows with every
-- completed job and claiming gets slower the more work you have done. With it,
-- the index holds only the backlog.
CREATE INDEX jobs_claim_idx
    ON jobs (priority, next_attempt_at, id)
    WHERE status = 'pending';

-- The reaper's index: running jobs whose lease has lapsed. Also partial, so it
-- holds only in-flight rows -- bounded by (workers x concurrency), i.e. dozens.
CREATE INDEX jobs_lease_idx
    ON jobs (lease_expires_at)
    WHERE status = 'running';

-- Idempotent enqueue. Scanning a folder twice, or a retried API call, must not
-- double the queue. Partial on the live states so that a job which has already
-- succeeded can legitimately be enqueued again later (a rescan after the file
-- changed), while an outstanding one cannot be duplicated.
CREATE UNIQUE INDEX jobs_dedupe_idx
    ON jobs (dedupe_key)
    WHERE status IN ('pending', 'running');

-- Progress reporting: SELECT job_type, status, count(*) GROUP BY 1, 2.
CREATE INDEX jobs_progress_idx
    ON jobs (library_id, job_type, status);

-- Finding a worker's in-flight jobs, for lease renewal and for releasing them
-- on graceful shutdown.
CREATE INDEX jobs_leased_by_idx
    ON jobs (leased_by)
    WHERE status = 'running';

CREATE TRIGGER jobs_set_updated_at
    BEFORE UPDATE ON jobs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- job_executions: an append-only audit of every attempt.
--
-- Not strictly required to run the queue, and included deliberately: it is the
-- evidence for the crash-recovery test. Asserting "no job was ever run by two
-- workers at the same time" needs a record of who ran what and when, which the
-- jobs table alone cannot provide because it only holds the latest attempt.
--
-- It also makes at-least-once execution observable rather than theoretical --
-- you can point at the row where a job ran twice and see that the outcome was
-- identical.
-- ---------------------------------------------------------------------------
CREATE TABLE job_executions (
    id        bigserial PRIMARY KEY,
    job_id    bigint NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    worker_id uuid   NOT NULL,
    attempt   int    NOT NULL,

    started_at  timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    -- NULL while running, then 'succeeded' | 'failed' | 'abandoned'.
    -- 'abandoned' is recorded by the reaper when a lease expires: the execution
    -- never reported an outcome because its worker died.
    outcome text CHECK (outcome IS NULL OR outcome IN ('succeeded', 'failed', 'abandoned')),
    error   text
);

CREATE INDEX job_executions_job_idx ON job_executions (job_id, started_at);
CREATE INDEX job_executions_worker_idx ON job_executions (worker_id);
