package store

import (
	"context"
	"fmt"
	"time"
)

// Worker is a registered worker process.
type Worker struct {
	ID              string     `json:"id"`
	Hostname        string     `json:"hostname"`
	PID             int        `json:"pid"`
	Status          string     `json:"status"`
	Concurrency     int        `json:"concurrency"`
	StartedAt       time.Time  `json:"started_at"`
	LastHeartbeatAt time.Time  `json:"last_heartbeat_at"`
	StoppedAt       *time.Time `json:"stopped_at,omitempty"`

	// RunningJobs is filled in by ListWorkers.
	RunningJobs int `json:"running_jobs"`
}

// RegisterWorker records a worker at startup.
//
// The id is generated by the worker, not the database, so that a retried
// registration is idempotent -- ON CONFLICT re-activates the same row rather
// than creating a second identity for the same process.
func (s *Store) RegisterWorker(ctx context.Context, id, hostname string, pid, concurrency int) error {
	const q = `
		INSERT INTO workers (id, hostname, pid, concurrency, status, last_heartbeat_at)
		VALUES ($1, $2, $3, $4, 'active', now())
		ON CONFLICT (id) DO UPDATE SET
			status            = 'active',
			hostname          = EXCLUDED.hostname,
			pid               = EXCLUDED.pid,
			concurrency       = EXCLUDED.concurrency,
			last_heartbeat_at = now(),
			stopped_at        = NULL`

	if _, err := s.pool.Exec(ctx, q, id, hostname, pid, concurrency); err != nil {
		return fmt.Errorf("store: registering worker: %w", err)
	}
	return nil
}

// Heartbeat records that a worker is still alive.
//
// Returns false when the row no longer says 'active' -- meaning the reaper
// already declared this worker dead. The worker treats that as a signal that
// its leases have been taken and it should stop claiming new work, rather than
// carrying on as a zombie competing with the replacement.
func (s *Store) Heartbeat(ctx context.Context, workerID string) (stillActive bool, err error) {
	const q = `
		UPDATE workers
		SET last_heartbeat_at = now()
		WHERE id = $1 AND status = 'active'`

	tag, err := s.pool.Exec(ctx, q, workerID)
	if err != nil {
		return false, fmt.Errorf("store: heartbeat: %w", err)
	}
	return tag.RowsAffected() == 1, nil
}

// UnregisterWorker marks a worker stopped on clean shutdown.
//
// Distinct from 'dead': a worker that says goodbye released its leases first,
// so its work was reassigned immediately rather than waiting out a lease.
// Keeping the two apart makes "did this worker crash or exit cleanly?"
// answerable from the database.
func (s *Store) UnregisterWorker(ctx context.Context, workerID string) error {
	const q = `
		UPDATE workers
		SET status = 'stopped', stopped_at = now()
		WHERE id = $1`

	if _, err := s.pool.Exec(ctx, q, workerID); err != nil {
		return fmt.Errorf("store: unregistering worker: %w", err)
	}
	return nil
}

// ReapDeadWorkers marks workers that have stopped heartbeating.
//
// This does NOT touch their jobs. Lease expiry handles that independently and
// on its own schedule, which keeps the two mechanisms decoupled: a worker
// pausing long enough to look dead does not instantly lose work it is still
// legitimately holding a valid lease on.
func (s *Store) ReapDeadWorkers(ctx context.Context, threshold time.Duration) (int, error) {
	const q = `
		UPDATE workers
		SET status = 'dead', stopped_at = now()
		WHERE status = 'active'
		  AND last_heartbeat_at < now() - $1::interval`

	tag, err := s.pool.Exec(ctx, q, threshold)
	if err != nil {
		return 0, fmt.Errorf("store: reaping dead workers: %w", err)
	}
	return int(tag.RowsAffected()), nil
}

// ListWorkers returns workers with their current job counts, most recent first.
func (s *Store) ListWorkers(ctx context.Context) ([]Worker, error) {
	const q = `
		SELECT w.id, w.hostname, w.pid, w.status, w.concurrency,
		       w.started_at, w.last_heartbeat_at, w.stopped_at,
		       (SELECT count(*) FROM jobs j
		        WHERE j.leased_by = w.id AND j.status = 'running') AS running_jobs
		FROM workers w
		ORDER BY
			-- Active workers first, then most recently seen.
			CASE w.status WHEN 'active' THEN 0 WHEN 'stopped' THEN 1 ELSE 2 END,
			w.last_heartbeat_at DESC`

	rows, err := s.pool.Query(ctx, q)
	if err != nil {
		return nil, fmt.Errorf("store: listing workers: %w", err)
	}
	defer rows.Close()

	out := []Worker{}
	for rows.Next() {
		var w Worker
		if err := rows.Scan(&w.ID, &w.Hostname, &w.PID, &w.Status, &w.Concurrency,
			&w.StartedAt, &w.LastHeartbeatAt, &w.StoppedAt, &w.RunningJobs); err != nil {
			return nil, fmt.Errorf("store: scanning worker: %w", err)
		}
		out = append(out, w)
	}
	return out, rows.Err()
}

// PurgeOldWorkers removes long-gone worker rows so the table does not grow
// without bound across restarts. Only touches terminal rows.
func (s *Store) PurgeOldWorkers(ctx context.Context, olderThan time.Duration) (int, error) {
	const q = `
		DELETE FROM workers
		WHERE status IN ('stopped', 'dead')
		  AND stopped_at < now() - $1::interval
		  -- Never delete a worker that still owns a job row, or the
		  -- ON DELETE SET NULL would silently orphan a live lease.
		  AND NOT EXISTS (
		      SELECT 1 FROM jobs j WHERE j.leased_by = workers.id AND j.status = 'running'
		  )`

	tag, err := s.pool.Exec(ctx, q, olderThan)
	if err != nil {
		return 0, fmt.Errorf("store: purging old workers: %w", err)
	}
	return int(tag.RowsAffected()), nil
}
